GEUsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),

    #Gestion de archivos
    path('viewGestionArchivo', views.viewGestionArchivo, name='viewGestionArchivo'),

    #Gestion de usuarios
    path('viewGestionUsuario', views.viewGestionUsuario, name='viewGestionUsuario'),

    #Plan de formacion
    path('viewSeccionModulo', views.viewSeccionModulo, name='viewSeccionModulo'),
    path('viewSeccionLecciones', views.viewSeccionLecciones, name='viewSeccionLecciones'),
]

polls/models.py
import uuid
from django.db import models
from django.contrib.auth.models import AbstractUser, Group, User
# Create your models here.
from GEUsite import settings

#
# class tipoUsuario(models.Model):
#     idTipoUsuario = models.AutoField(primary_key=True)
#     tipoUsuario = models.CharField(max_length=20, null=False, blank=False)
#     estado = models.BooleanField(default=True)

# class perfil(models.Model):
#     #fkGroup = models.OneToOneField(Group, on_delete= models.PROTECT)
#     fkTipoUsuario= models.OneToOneField(tipoUsuario,on_delete=models.PROTECT, null=False,
#                                       related_name='tipoUsuario_usuario')
#     fkUsuario = models.OneToOneField(settings.AUTH_USER_MODEL,on_delete=models.PROTECT, null=False,
#                                       related_name='usuario_TipoUsuario')
#     estado = models.BooleanField(default=True)
class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    title = models.CharField(max_length=50)
    content= models.TextField()
    def __str__(self):
        return self.title

class modulo(models.Model):
    idModulo = models.UUIDField(primary_key=True, default=uuid.uuid4)
    nombreModulo = models.CharField(max_length=20, null=False, blank=False)
    descripcion = models.CharField(max_length=100, null=False, blank=False)
    estado = models.BooleanField(default=True)


class tipoLeccion(models.Model):
    idTipoLeccion = models.UUIDField(primary_key=True, default=uuid.uuid4)
    tipoLeccion = models.CharField(max_length=20, null=False, blank=False)
    estado = models.BooleanField(default=True)

class respuesta(models.Model):
    idRespuesta = models.UUIDField(primary_key=True, default=uuid.uuid4)
    fkUsuario = models.ForeignKey(User, on_delete=models.PROTECT,
                                  related_name='respuesta_usuario')
    respuesta = models.CharField(max_length=200, null=False, blank=False)
    estado = models.CharField(max_length=100, null=False, blank=False)

class leccion(models.Model):
    fkTipoLeccion = models.ForeignKey(tipoLeccion, on_delete=models.PROTECT)
    fkRespuesta = models.ForeignKey(respuesta, on_delete=models.PROTECT)
    idLeccion = models.UUIDField(primary_key=True, default=uuid.uuid4)
    nombreLeccion = models.CharField(max_length=20, null=False, blank=False)
    descripcion = models.CharField(max_length=100, null=False, blank=False)
    estado = models.BooleanField(default=True)

class archivos(models.Model):
    fkUsuarioCreacion = models.ForeignKey(User, on_delete=models.PROTECT,
                                          related_name='archivos_usuario_creacion')
    idArchivo = models.UUIDField(primary_key=True, default=uuid.uuid4)
    nombreArchivo = models.CharField(max_length=20, null=False, blank=False)
    descripcion = models.CharField(max_length=100, null=False, blank=False)
    archivo = models.FileField()
    estado = models.BooleanField(default=True)
    fechaCreacion = models.DateTimeField(auto_now_add=True)
    fechaEdicion = models.DateTimeField(auto_now_add=True)

polls/views.py
from django.shortcuts import render
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import *
from django.shortcuts import render, redirect, get_object_or_404
# Create your views here.
from django.http import HttpResponse
from django.contrib import messages

def index(request):
    if request.method == "GET":
        return render(request, 'geuSite/index.html')
    #gestion de archivos
def viewGestionArchivo(request):
    if request.method == "GET":
        archivosRegistrados = archivos.objects.all()
        return render(request, 'geuSite/gestionArchivo/gestionArchivo.html',{'archivosRegistrados': archivosRegistrados})

    #gestion de usuarios
def viewGestionUsuario(request):
    if request.method == "GET":
        usuariosRegistrados = archivos.objects.all()
        return render(request, 'geuSite/gestionUsuario/gestionUsuario.html',
                          {'usuariosRegistrados': usuariosRegistrados})

    #plan de formacion
def viewSeccionModulo(request):
    if request.method == "GET":
        return render(request, 'geuSite/planDeFormacion/modulo.html')

def viewSeccionLecciones(request):
    if request.method == "GET":
        return render(request, 'geuSite/planDeFormacion/Lecciones.html')

polls/templates/geuSite/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'geuSite/plugins/fontawesome-free/css/all.min.css' %}">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet"
          href="{% static 'geuSite/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
    <link rel="stylesheet" href="{% static 'core/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'geuSite/plugins/jqvmap/jqvmap.min.css' %}">
    <link rel="stylesheet" href="{% static 'geuSite/dist/css/adminlte.css' %}">
    <link rel="stylesheet" href="{% static 'geuSite/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
    <link rel="stylesheet" href="{% static 'geuSite/plugins/daterangepicker/daterangepicker.css' %}">
    <link rel="stylesheet" href="{% static 'geuSite/plugins/summernote/summernote-bs4.css' %}">
    <link rel="stylesheet" href="{% static 'geuSite/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css' %}">
    <link rel="stylesheet" href="{% static 'geuSite/plugins/datatables-bs4/css/dataTables.bootstrap4.css' %}">
    <link rel="stylesheet" href="{% static 'geuSite/plugins/datatables-responsive/css/responsive.bootstrap4.css' %}">
    <link rel="stylesheet" href="{% static 'geuSite/plugins/select2/css/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'geuSite/dist/css/cssCustom.css' %}">
    <link rel="icon" type="image/png" href="{% static 'geuSite/dist/img/favicon.ico' %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <script></script>
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">
    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-blue navbar-purple">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" role="button"><i class="fas fa-bars"></i></a>
            </li>
        </ul>
    </nav>

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary  navbar-purple elevation-4">
        <!-- Brand Logo -->
        <a class="brand-link" href="{% url 'polls:index' %}">
            <img src="{% static 'geuSite/img/geuLogo.png' %}" class="brand-image img-circle elevation-3"
                 style="opacity: 5">
            <span class="brand-text font-weight-light">Geu Site</span>

        </a>

        <!-- Sidebar -->
        <div class="sidebar">
            <!-- Sidebar Menu -->
            <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                    data-accordion="false">
                    <li class="nav-header">

                                Aprendizaje
                                <!--                                Bienvenido {{ user.username }}-->
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'polls:viewSeccionModulo' %}" class="nav-link">
                            <i class="fas fa-map-signs"></i>
                            <p>
                                Plan de formación
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="fas fa-copy"></i>
                            <p>
                                Archivos
                            </p>
                        </a>
                    </li>
                    <li class="nav-header">Herramientas</li>
                    <li class="nav-item">
                        <a href="{% url 'polls:viewGestionUsuario' %}" class="nav-link">
                            <i class="fas fa-user-friends"></i>
                            <p>
                                Gestión de Usuarios
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'polls:viewGestionArchivo' %}" class="nav-link">
                            <i class="fas fa-cloud"></i>
                            <p>
                                Gestión de Archivos
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="fas fa-database"></i>
                            <p>
                                Reportes
                            </p>
                        </a>
                    </li>
                    <li class="nav-header">

                                Opciones
                                <!--                                Bienvenido {{ user.username }}-->
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="fas fa-sign-out-alt"></i>
                            <p>
                                Cerrar Sesión
                            </p>
                        </a>
                    </li>
                </ul>
            </nav>
            <!-- /.sidebar-menu -->
        </div>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                {% block content %}
                {% endblock content %}
            </div>
        </section>
        <!-- /.content -->
    </div>

    <!-- /.content-wrapper -->
    <footer class="main-footer">
        <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong>
        All rights reserved.
        <div class="float-right d-none d-sm-inline-block">
            <b>Version</b> 3.0.5
        </div>
    </footer>

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->


    <!-- messages of confirmation or error -->
    {% if messages %}
    {% for message in messages %}
    {% if message.tags == 'success' %}
    <script>
                    setTimeout(function () {
                        Swal.fire({
                            title: 'Mensaje',
                            text: '{{ message | safe }}',
                            icon: 'success',
                            confirmButtonText: 'Aceptar',
                        })
                    }, 800);

    </script>
    {% elif message.tags == 'error' %}
    <script>
                    setTimeout(function () {
                        Swal.fire({
                            title: 'Error',
                            text: '{{ message | safe }}',
                            icon: 'error',
                            confirmButtonText: 'Aceptar',
                        });
                    }, 800);

    </script>
    {% endif %}
    {% endfor %}
    {% endif %}

    <!-- modals of delete and update CRUD -->
    <div class="modal fade" id="deleteModal">

    </div>
    <div class="modal fade" id="updateModal">

    </div>

</div>
<!-- ./wrapper -->
<!-- jQuery -->
<script src="{% static 'geuSite/plugins/jquery/jquery.min.js' %}"></script>
<!-- inputMinJS-->
<script src="{% static 'geuSite/plugins/bs-custom-file-input/bs-custom-file-input.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'geuSite/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button)

</script>
<script src="{% static 'geuSite/js/passwordValidator.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'geuSite/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- Sparkline -->
<script src="{% static 'geuSite/plugins/sparklines/sparkline.js' %}"></script>
<!-- JQVMap -->
<script src="{% static 'geuSite/plugins/jqvmap/jquery.vmap.min.js' %}"></script>
<script src="{% static 'geuSite/plugins/jqvmap/maps/jquery.vmap.usa.js' %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static 'geuSite/plugins/jquery-knob/jquery.knob.min.js' %}"></script>
<!-- daterangepicker -->
<script src="{% static 'geuSite/plugins/moment/moment.min.js' %}"></script>
<script src="{% static 'geuSite/plugins/daterangepicker/daterangepicker.js' %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static 'geuSite/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
<!-- Summernote -->
<script src="{% static 'geuSite/plugins/summernote/summernote-bs4.min.js' %}"></script>
<!-- overlayScrollbars -->
<script src="{% static 'geuSite/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'geuSite/dist/js/adminlte.js' %}"></script>
<!-- Datatable -->
<script src="{% static 'geuSite/plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'geuSite/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'geuSite/plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'geuSite/plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'geuSite/plugins/pdfmake/pdfmake.min.js' %}"></script>
<script src="{% static 'geuSite/plugins/pdfmake/vfs_fonts.js' %}"></script>
<script src="{% static 'geuSite/plugins/sweetalert2/sweetalert2.all.js' %}"></script>
<script src="{% static 'geuSite/plugins/select2/js/select2.full.min.js' %}"></script>
<script src="{% static 'geuSite/js/main.js' %}"></script>
<script type="text/javascript">
    bsCustomFileInput.init();

</script>
</body>
</html>

polls/templates/geuSite/gestionArchivo/gestionArchivo.html
{% extends "geuSite/base.html" %}
{% load static %}
{% block title %}Gestion de Archivos{% endblock title %}
{% block titlePage %}Gestion de Archivos{% endblock titlePage %}
{% block content %}
<section>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h4>Archivos Registrados</h4>
                    <div class="col-lg-3">
                        <button type="button" class="btn btn-block btn-info" data-toggle="modal"
                                data-target="#modal-ingresar"><i class="fas fa-plus"></i>
                            Subir Archivo
                        </button>
                    </div>
                </div>
                <div class="card-body">
                    <table id="tabla" class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>Nombre Archivo</th>
                            <th>Descripcion</th>
                            <th>Opciones</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for archivo in archivosRegistrados %}
                        <tr>
                            <td>Ejemplo</td>
                            <td>{{ archivo.nombreArchivo }}</td>
                            <td>{{ archivo.descripcion }}</td>
                            <td>
                                <div class="text-center">
                                    <button class="updateClient btn btn-warning text-white">
                                        <!--                                                    onclick="activateUpdateModal('{% url 'inventory:viewUpdateBrand' brand.idBrand %}')">-->
                                        <i
                                                class="fas fa-edit"></i>
                                        Actualizar
                                    </button>
                                    <button class="deleteClient btn btn-danger text-white">
                                        <!--                                                    onclick="activateDeleteModal('{% url 'inventory:viewDeleteBrand' brand.idBrand %}')">-->
                                        <i
                                                class="fas fa-trash-alt"></i>
                                        Eliminar
                                    </button>
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>
{# modal crear #}
<section>
    <form method="post" action="#">
        {% csrf_token %}
        <div class="modal fade" id="modal-ingresar">
            <div class="modal-dialog" style="max-width: 600px;">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Subir Archivo</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <label>Nombre Archivo</label>
                            <input type="text" class="form-control" name="nombreArchivo"
                                   placeholder="Ingrese nombre del archivo">
                            <label>Descripción</label>
                            <input type="text" class="form-control" name="nombreArchivo"
                                   placeholder="Ingrese nombre del archivo">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputFile">File input</label>
                            <div class="input-group">
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input" id="exampleInputFile">
                                    <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                                </div>
                                <div class="input-group-append">
                                    <span class="input-group-text" id="">Upload</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer justify-content-between">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                        <button type="submit" class="btn btn-primary">Guardar archivo</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</section>
{% endblock content %}

polls/templates/geuSite/gestionUsuario/gestionUsuario.html
{% extends "geuSite/base.html" %}
{% load static %}
{% block title %}Gestion de Usuarios{% endblock title %}
{% block titlePage %}Gestion de Usuarios{% endblock titlePage %}
{% block content %}
<section>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h4>Usuarios Registrados</h4>
<!--                    <div class="col-lg-3">-->
<!--                        <button type="button" class="btn btn-block btn-info" data-toggle="modal"-->
<!--                                data-target="#modal-ingresar"><i class="fas fa-plus"></i>-->
<!--                            Subir Archivo-->
<!--                        </button>-->
<!--                    </div>-->
                </div>
                <div class="card-body">
                    <table id="tabla" class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>Usuario</th>
                            <th>Tipo de usuario</th>
                            <th>Nombres</th>
                            <th>Apellidos</th>
                            <th>Opciones</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for usuario in usuariosRegistrados %}
                        <tr>
                            <td>{{usuario.username}}</td>
<!--                            <td>{{ usuario.last_name }}</td>-->
                            <td>{{ usuario.first_name }}</td>
                            <td>{{ usuario.last_name }}</td>
                            <td>
                                <div class="text-center">
                                    <button class="updateClient btn btn-warning text-white">
                                        <!--                                                    onclick="activateUpdateModal('{% url 'inventory:viewUpdateBrand' brand.idBrand %}')">-->
                                        <i
                                                class="fas fa-edit"></i>
                                        Actualizar
                                    </button>
                                    <button class="deleteClient btn btn-danger text-white">
                                        <!--                                                    onclick="activateDeleteModal('{% url 'inventory:viewDeleteBrand' brand.idBrand %}')">-->
                                        <i
                                                class="fas fa-trash-alt"></i>
                                        Eliminar
                                    </button>
                                </div>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>
{# modal crear #}
<!--<section>-->
<!--    <form method="post" action="#">-->
<!--        {% csrf_token %}-->
<!--        <div class="modal fade" id="modal-ingresar">-->
<!--            <div class="modal-dialog" style="max-width: 600px;">-->
<!--                <div class="modal-content">-->
<!--                    <div class="modal-header">-->
<!--                        <h4 class="modal-title">Subir Archivo</h4>-->
<!--                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">-->
<!--                            <span aria-hidden="true">&times;</span>-->
<!--                        </button>-->
<!--                    </div>-->
<!--                    <div class="modal-body">-->
<!--                        <div class="form-group">-->
<!--                            <label>Nombre Archivo</label>-->
<!--                            <input type="text" class="form-control" name="nombreArchivo"-->
<!--                                   placeholder="Ingrese nombre del archivo">-->
<!--                            <label>Descripción</label>-->
<!--                            <input type="text" class="form-control" name="nombreArchivo"-->
<!--                                   placeholder="Ingrese nombre del archivo">-->
<!--                        </div>-->
<!--                        <div class="form-group">-->
<!--                            <label for="exampleInputFile">File input</label>-->
<!--                            <div class="input-group">-->
<!--                                <div class="custom-file">-->
<!--                                    <input type="file" class="custom-file-input" id="exampleInputFile">-->
<!--                                    <label class="custom-file-label" for="exampleInputFile">Choose file</label>-->
<!--                                </div>-->
<!--                                <div class="input-group-append">-->
<!--                                    <span class="input-group-text" id="">Upload</span>-->
<!--                                </div>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                    <div class="modal-footer justify-content-between">-->
<!--                        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>-->
<!--                        <button type="submit" class="btn btn-primary">Guardar archivo</button>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </form>-->
<!--</section>-->
{% endblock content %}

polls/templates/geuSite/index.html
{% extends "geuSite/base.html" %}
{% load static %}
{% block title %}GeuSite{% endblock title %}
{% block content %}
    <section class="content">
        <div class="row">
            <div class="col-lg-12 col-xs-6">
                <h1 class="text-center">Bienvenido</h1>
            </div>
                <div class="col-lg-3 col-xs-6">
                    <!-- small box -->
                    <div class="small-box bg-gradient-lightblue">
                        <div class="inner">
                            <h3>que</h3>
                            <p><br></p>
                        </div>
                        <div class="icon">
                            <i class="fas fa-user-check"></i>
                        </div>
                        <p class="small-box-footer">Usuario</p>
                    </div>
                </div>
            <div class="col-lg-3 col-xs-6">
                    <!-- small box -->
                    <div class="small-box bg-gradient-orange">
                        <div class="inner">
                            <h3>que</h3>
                            <p><br></p>
                        </div>
                        <div class="icon">
                            <i class="fas fa-user-check"></i>
                        </div>
                        <p class="small-box-footer">Usuario</p>
                    </div>
                </div>
            <div class="col-lg-3 col-xs-6">
                    <!-- small box -->
                    <div class="small-box bg-gradient-red">
                        <div class="inner">
                            <h3>que</h3>
                            <p><br></p>
                        </div>
                        <div class="icon">
                            <i class="fas fa-user-check"></i>
                        </div>
                        <p class="small-box-footer">Usuario</p>
                    </div>
                </div>
        </div>
    </section>
{% endblock content %}

polls/templates/geuSite/planDeFormacion/Lecciones.html
{% extends "geuSite/base.html" %}
{% load static %}
{% block title %}Lecciones{% endblock title %}
{% block titlePage %}Lecciones{% endblock titlePage %}
{% block content %}
    <section>
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4>Sección de Lecciones</h4>
                    </div>
                    <div class="card-body">
                        
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock content %}

polls/templates/geuSite/planDeFormacion/modulo.html
{% extends "geuSite/base.html" %}
{% load static %}
{% block title %}Modulos{% endblock title %}
{% block titlePage %}Modulos{% endblock titlePage %}
{% block content %}
<section>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h4>Sección de Módulos</h4>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="card card-primary collapsed-card">
                                <div class="card-header">
                                    <h3 class="card-title">Módulo 1</h3>
                                    <div class="card-tools">
                                        <button type="button" class="btn btn-tool" data-card-widget="collapse"><i
                                                class="fas fa-plus"></i>
                                        </button>
                                    </div>
                                    <!-- /.card-tools -->
                                </div>
                                <!-- /.card-header -->
                                <div class="card-body">
                                    Descripcion del modulo jejejeje
                                </div>
                                <!-- /.card-body -->
                                <div class="small-box bg-primary">
                                    <a href="{% url 'polls:viewSeccionLecciones' %}"" class="small-box-footer">
                                        Ingresar <i class="fas fa-arrow-circle-right"></i>
                                    </a>
                                </div>
                            </div>
                            <!-- /.card -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}